### PR TITLE
FR langage translation

### LINKED ISSUE #44: French translation incomplete
The french translation is missing a few new things.

@MetallicaMust Could you adjust the french translation so it matches the new version? I have changed a few things and there are new translation files that are missing in the french version. My french is not good enough to do this myself.

### PR DESCRIPTION
**Pull request by ChristopheTdn**
> Only 2 files to my side in french translation directory added. Let me known if i made a mistake.

https://github.com/gn36/phpbb-ext-hookup/commit/b4e469c81b9d290f1e610d59bb298fa15733f125

next file later ;-)

Fixes #44

### CODE REVIEW

**Comment by ChristopheTdn** [comment]
sending the second part of traduction : 
https://github.com/ChristopheTdn/phpbb-ext-hookup/commit/547ac4fe7b67fb67ca6ee3b314e089a28ecc7049

**Comment by gn36** [comment]
Looks almost perfect :)

There is only two errors left:

> Fatal in hookup.php:USERNAMES_EXPLAIN:
> String is using additional html: <span style="text-decoration: underline;">
> Fatal in hookup.php:
> Must contain key: HOOKUP_AUTORESET_ACTIVE_DESC

So please add the missing translation for HOOKUP_AUTORESET_ACTIVE_DESC (almost at the bottom of hookup.php, below 'HOOKUP_AUTORESET_DESC') and ideally also remove the < span style=...>< /span> from USERNAMES_EXPLAIN

After that I will merge. Thanks again!

Fixes #44

**Comment by ChristopheTdn** [comment]
last change online. give it a try and let me known if there s a problem.

Thx for your work !!!

**Comment by gn36** [comment]
Thank you for the translation, only one minor error left, I correct that myself.

**Pull request merged**
