### PR TITLE
Text choice

### LINKED ISSUE #4: Allow entry of arbitrary text instead of date/time for the list
Instead of only permitting date and time for entries, it should also be possible to enter arbitrary text so that more customized questions can be adressed, similar to a poll where multiple options can be selected.

This was also possible using a modification by miriam to the original phpBB 3 Mod. However the zip archive containing the changes is no longer available. It would be nice to make this compatible to the old variant to allow upgrades.

Possibly someone can provide the complete zip archive?

Related: http://pastebin.com/NB3zHJ42

### PR DESCRIPTION
**Pull request by kilianr**
I added functionality to specify text entries instead of only date entries. Text entries can be added by appending a '#' caracter. So

```
2015-08-26 12:00
# foo bar
```

will add one date entry and one entry with the text "foo bar".
This solves issue #4.

Two notes:
1. The schema changes have been directly modified in migrations/v_1_0_0_compat30x.php. If versioning is already important, this can easily splitted into a different migrations file.
2. The cron-job code looks strange to me and I'm not sure if the changes I made there will work as expected.

Fixes #4

### CODE REVIEW

**Comment by gn36** [comment]
Very nice, thank you!

I think the migration file should not be modified - not necessarily because of versioning but because I want this extension to be backwards compatible to the old mod. This database change is not present in all 3.0.x Versions of this extension, therefore it should go into a separate migration so it won't break upgrades, regardless of whether the database change is already present in older versions or not. I think there may be some older versions that have a similar modification in them so maybe it is even worthwile checking that in the migration to allow those people to upgrade as well, if the database field is named the same (I did not check that).

Also, could you please add a default parameter "null" to the add_date method in functions/hookup?

> public function add_date($date, $text = null)

 Otherwise this change will break all my custom scripts I am using on my own site to add a new hookup to a topic.

The description is a little bit misleading I think. I would not understand that the # is required for text, nor that this allows text to be entered. I think the following would be better:

> Hiermit fügst du neue Datumsvorschläge oder Beschreibungen in die Liste ein. Gib pro Zeile ein Datum im Format TT.MM.JJJJ ss:mm, JJJJ-MM-TT ss:mm oder füge eine Option mit Beschreibungstext ein, indem du am Anfang der Zeile ein # einfügst.
> Datum/Beschreibung ungültig. Das Datum muss im Format TT.MM.JJJJ SS:MM, JJJJ-MM-TT SS:MM angegeben werden. Vor Textangaben muss ein # eingefügt werden.

Obviously, a similar change for english:

> Here you can propose new dates or options with descriptive text. Enter one date per line in DD.MM.YYYY hh:mm, YYYY-MM-DD hh:mm format or prepend a # to enter an option in text format.
> Invalid date/description. Please enter date in DD.MM.YYYY HH:MM, YYYY-MM-DD HH:MM or prepend a # in front of descriptive texts.

I am not sure whether the cronjob is actually doing what it is supposed to do, yet. I still have to test that, so if you find it strange, you may be correct that it is not doing what it is supposed to do. I am not sure how the cronjob should react to text options since those don't contain a date. Unless we allow a combination of date and text I don't see how this should be repeated weekly. 

You should probably also add yourself to the authors list in the json file since this is more than just a small change :)

**Comment by gn36** [comment]
I just checked the old version: It seems there the text field was named "description". We don't need to stick to this name, but the new migration should check for that in a custom function and convert. I can take care of that if you want, though.

**Comment by kilianr** [comment]
Ok, I've changed the files to implement your suggestions.
Since I don't have an legacy database with a 'description' column, I didn't implmented a convert function for that field because I would not be able to test it properly. So I would be glad if you could in fact take care of it.

**Comment by gn36** [comment]
Thank you again :)

Actually the migration should not be named v_1_0_1, because we are still working on Version 1.0.0. (that is why it is called version 1.0.0-dev, because Version 1.0.0 is not yet finished) I should not have named migration v_1_0_0 the way I have, but without breaking everyones board who is already using this, there is no real way to change this, so it will stay this way. But here we can still change this, so please rename it to something like v_1_0_0_textoptions or so. The Version should still stay at 1.0.0-dev as well for now.

I will take care of the change to the migration for conversion of the "description" column.

**Comment by kilianr** [comment]
I read again about the migration policy in phpBB, now I get how those files are supposed to work :-)
So the version is back to 1.0.0-dev and the branch should be ready for a merge.

**Comment by kilianr** [comment]
Still had to fix a bug concerning the table_prefix. Now, all work (at least, on my machine :-) ).

**Comment by gn36** [comment]
Allright, the only thing that is still missing is a "revert_schema" method in the new migration. I guess uninstalling and reinstalling still works because the other migration will completely drop the table, but if something goes wrong during an update it would be better if the migration removed its changes itself. So please add a drop_column statement to the migration. Everything else seems well - I will test it in a couple of days and then merge it.

**Comment by kilianr** [comment]
Ok, revert_schema with drop_columns is added.

**Comment by gn36** [comment]
Perfect, I will test and then merge this soon.
@MetallicaMust: This merge will require a slight change on the french translations on 'HOOKUP_ADD_DATES_EXPLAIN' and 'INVALID_DATE' in language/fr/hookup.php

See: https://github.com/gn36/phpbb-ext-hookup/pull/28/files#diff-ea296f57211d2d180744e8e55452197fR43 for the changes.

**Comment by lofcz** [comment]
Nice work.

**Comment by ghost** [comment]
I am there and it will be made from here tomorrow ;-)

**Comment by lofcz** [comment]
Have you really started working on time feature? 
Excellent work, sir.

**Comment by gn36** [comment]
I have been busy with replacing the old emailing system by notifications, so I haven't taken care of the time based deny of changes, if that is what you meant.

Please check the [issues](https://github.com/gn36/phpbb-ext-hookup/issues) tab and try to pick the appropriate issue when commenting so you don't accidentally highlight people who don't need to read your comment. 

I have assigned the features to milestones to show how the approximate schedule of features will look like.

**Pull request merged**
